// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Competition;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Competition_Roo_Configurable {
    
    declare @type: Competition: @Configurable;
    
}
