// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Competition;
import com.atreceno.it.diaulos.domain.CompetitionDataOnDemand;
import com.atreceno.it.diaulos.domain.CompetitionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CompetitionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CompetitionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CompetitionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: CompetitionIntegrationTest: @Transactional;
    
    @Autowired
    CompetitionDataOnDemand CompetitionIntegrationTest.dod;
    
    @Test
    public void CompetitionIntegrationTest.testCountCompetitions() {
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = Competition.countCompetitions();
        Assert.assertTrue("Counter for 'Competition' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindCompetition() {
        Competition obj = dod.getRandomCompetition();
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = Competition.findCompetition(id);
        Assert.assertNotNull("Find method for 'Competition' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Competition' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindAllCompetitions() {
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = Competition.countCompetitions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Competition', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Competition> result = Competition.findAllCompetitions();
        Assert.assertNotNull("Find all method for 'Competition' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Competition' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CompetitionIntegrationTest.testFindCompetitionEntries() {
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        long count = Competition.countCompetitions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Competition> result = Competition.findCompetitionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Competition' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Competition' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CompetitionIntegrationTest.testFlush() {
        Competition obj = dod.getRandomCompetition();
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = Competition.findCompetition(id);
        Assert.assertNotNull("Find method for 'Competition' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCompetition(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Competition' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetitionIntegrationTest.testMergeUpdate() {
        Competition obj = dod.getRandomCompetition();
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = Competition.findCompetition(id);
        boolean modified =  dod.modifyCompetition(obj);
        Integer currentVersion = obj.getVersion();
        Competition merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Competition' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CompetitionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", dod.getRandomCompetition());
        Competition obj = dod.getNewTransientCompetition(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Competition' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Competition' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Competition' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CompetitionIntegrationTest.testRemove() {
        Competition obj = dod.getRandomCompetition();
        Assert.assertNotNull("Data on demand for 'Competition' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Competition' failed to provide an identifier", id);
        obj = Competition.findCompetition(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Competition' with identifier '" + id + "'", Competition.findCompetition(id));
    }
    
}
