// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Discipline;
import com.atreceno.it.diaulos.domain.DisciplineDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect DisciplineDataOnDemand_Roo_DataOnDemand {
    
    declare @type: DisciplineDataOnDemand: @Component;
    
    private Random DisciplineDataOnDemand.rnd = new SecureRandom();
    
    private List<Discipline> DisciplineDataOnDemand.data;
    
    public Discipline DisciplineDataOnDemand.getNewTransientDiscipline(int index) {
        Discipline obj = new Discipline();
        setDescription(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void DisciplineDataOnDemand.setDescription(Discipline obj, int index) {
        String description = "description_" + index;
        if (description.length() > 255) {
            description = description.substring(0, 255);
        }
        obj.setDescription(description);
    }
    
    public void DisciplineDataOnDemand.setName(Discipline obj, int index) {
        String name = "name_" + index;
        if (name.length() > 25) {
            name = name.substring(0, 25);
        }
        obj.setName(name);
    }
    
    public Discipline DisciplineDataOnDemand.getSpecificDiscipline(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Discipline obj = data.get(index);
        String id = obj.getCode();
        return Discipline.findDiscipline(id);
    }
    
    public Discipline DisciplineDataOnDemand.getRandomDiscipline() {
        init();
        Discipline obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getCode();
        return Discipline.findDiscipline(id);
    }
    
    public boolean DisciplineDataOnDemand.modifyDiscipline(Discipline obj) {
        return false;
    }
    
    public void DisciplineDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Discipline.findDisciplineEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Discipline' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Discipline>();
        for (int i = 0; i < 10; i++) {
            Discipline obj = getNewTransientDiscipline(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
