// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Discipline;
import com.atreceno.it.diaulos.domain.DisciplineDataOnDemand;
import com.atreceno.it.diaulos.domain.DisciplineIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DisciplineIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DisciplineIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DisciplineIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: DisciplineIntegrationTest: @Transactional;
    
    @Autowired
    DisciplineDataOnDemand DisciplineIntegrationTest.dod;
    
    @Test
    public void DisciplineIntegrationTest.testCountDisciplines() {
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", dod.getRandomDiscipline());
        long count = Discipline.countDisciplines();
        Assert.assertTrue("Counter for 'Discipline' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DisciplineIntegrationTest.testFindDiscipline() {
        Discipline obj = dod.getRandomDiscipline();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to provide an identifier", id);
        obj = Discipline.findDiscipline(id);
        Assert.assertNotNull("Find method for 'Discipline' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Discipline' returned the incorrect identifier", id, obj.getCode());
    }
    
    @Test
    public void DisciplineIntegrationTest.testFindAllDisciplines() {
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", dod.getRandomDiscipline());
        long count = Discipline.countDisciplines();
        Assert.assertTrue("Too expensive to perform a find all test for 'Discipline', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Discipline> result = Discipline.findAllDisciplines();
        Assert.assertNotNull("Find all method for 'Discipline' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Discipline' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DisciplineIntegrationTest.testFindDisciplineEntries() {
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", dod.getRandomDiscipline());
        long count = Discipline.countDisciplines();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Discipline> result = Discipline.findDisciplineEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Discipline' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Discipline' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DisciplineIntegrationTest.testFlush() {
        Discipline obj = dod.getRandomDiscipline();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to provide an identifier", id);
        obj = Discipline.findDiscipline(id);
        Assert.assertNotNull("Find method for 'Discipline' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDiscipline(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Discipline' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DisciplineIntegrationTest.testMergeUpdate() {
        Discipline obj = dod.getRandomDiscipline();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to provide an identifier", id);
        obj = Discipline.findDiscipline(id);
        boolean modified =  dod.modifyDiscipline(obj);
        Integer currentVersion = obj.getVersion();
        Discipline merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getCode(), id);
        Assert.assertTrue("Version for 'Discipline' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DisciplineIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", dod.getRandomDiscipline());
        Discipline obj = dod.getNewTransientDiscipline(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Discipline' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Discipline' identifier to be null", obj.getCode());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Discipline' identifier to no longer be null", obj.getCode());
    }
    
    @Test
    public void DisciplineIntegrationTest.testRemove() {
        Discipline obj = dod.getRandomDiscipline();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Discipline' failed to provide an identifier", id);
        obj = Discipline.findDiscipline(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Discipline' with identifier '" + id + "'", Discipline.findDiscipline(id));
    }
    
}
