// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.EventGender;
import com.atreceno.it.diaulos.domain.EventGenderDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect EventGenderDataOnDemand_Roo_DataOnDemand {
    
    declare @type: EventGenderDataOnDemand: @Component;
    
    private Random EventGenderDataOnDemand.rnd = new SecureRandom();
    
    private List<EventGender> EventGenderDataOnDemand.data;
    
    public EventGender EventGenderDataOnDemand.getNewTransientEventGender(int index) {
        EventGender obj = new EventGender();
        setName(obj, index);
        return obj;
    }
    
    public void EventGenderDataOnDemand.setName(EventGender obj, int index) {
        String name = "name_" + index;
        if (name.length() > 15) {
            name = name.substring(0, 15);
        }
        obj.setName(name);
    }
    
    public EventGender EventGenderDataOnDemand.getSpecificEventGender(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        EventGender obj = data.get(index);
        String id = obj.getCode();
        return EventGender.findEventGender(id);
    }
    
    public EventGender EventGenderDataOnDemand.getRandomEventGender() {
        init();
        EventGender obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getCode();
        return EventGender.findEventGender(id);
    }
    
    public boolean EventGenderDataOnDemand.modifyEventGender(EventGender obj) {
        return false;
    }
    
    public void EventGenderDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = EventGender.findEventGenderEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'EventGender' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<EventGender>();
        for (int i = 0; i < 10; i++) {
            EventGender obj = getNewTransientEventGender(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
