// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Medal;
import com.atreceno.it.diaulos.domain.MedalDataOnDemand;
import com.atreceno.it.diaulos.domain.MedalIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MedalIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MedalIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MedalIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MedalIntegrationTest: @Transactional;
    
    @Autowired
    MedalDataOnDemand MedalIntegrationTest.dod;
    
    @Test
    public void MedalIntegrationTest.testCountMedals() {
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", dod.getRandomMedal());
        long count = Medal.countMedals();
        Assert.assertTrue("Counter for 'Medal' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MedalIntegrationTest.testFindMedal() {
        Medal obj = dod.getRandomMedal();
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Medal' failed to provide an identifier", id);
        obj = Medal.findMedal(id);
        Assert.assertNotNull("Find method for 'Medal' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Medal' returned the incorrect identifier", id, obj.getCode());
    }
    
    @Test
    public void MedalIntegrationTest.testFindAllMedals() {
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", dod.getRandomMedal());
        long count = Medal.countMedals();
        Assert.assertTrue("Too expensive to perform a find all test for 'Medal', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Medal> result = Medal.findAllMedals();
        Assert.assertNotNull("Find all method for 'Medal' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Medal' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MedalIntegrationTest.testFindMedalEntries() {
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", dod.getRandomMedal());
        long count = Medal.countMedals();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Medal> result = Medal.findMedalEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Medal' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Medal' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MedalIntegrationTest.testFlush() {
        Medal obj = dod.getRandomMedal();
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Medal' failed to provide an identifier", id);
        obj = Medal.findMedal(id);
        Assert.assertNotNull("Find method for 'Medal' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMedal(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Medal' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MedalIntegrationTest.testMergeUpdate() {
        Medal obj = dod.getRandomMedal();
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Medal' failed to provide an identifier", id);
        obj = Medal.findMedal(id);
        boolean modified =  dod.modifyMedal(obj);
        Integer currentVersion = obj.getVersion();
        Medal merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getCode(), id);
        Assert.assertTrue("Version for 'Medal' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MedalIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", dod.getRandomMedal());
        Medal obj = dod.getNewTransientMedal(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Medal' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Medal' identifier to be null", obj.getCode());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Medal' identifier to no longer be null", obj.getCode());
    }
    
    @Test
    public void MedalIntegrationTest.testRemove() {
        Medal obj = dod.getRandomMedal();
        Assert.assertNotNull("Data on demand for 'Medal' failed to initialize correctly", obj);
        String id = obj.getCode();
        Assert.assertNotNull("Data on demand for 'Medal' failed to provide an identifier", id);
        obj = Medal.findMedal(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Medal' with identifier '" + id + "'", Medal.findMedal(id));
    }
    
}
