// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Medal;
import com.atreceno.it.diaulos.domain.MedalDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect MedalDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MedalDataOnDemand: @Component;
    
    private Random MedalDataOnDemand.rnd = new SecureRandom();
    
    private List<Medal> MedalDataOnDemand.data;
    
    public Medal MedalDataOnDemand.getNewTransientMedal(int index) {
        Medal obj = new Medal();
        setCode(obj, index);
        setName(obj, index);
        return obj;
    }
    
    public void MedalDataOnDemand.setCode(Medal obj, int index) {
        String code = String.valueOf(index);
        if (code.length() > 1) {
            code = code.substring(0, 1);
        }
        obj.setCode(code);
    }
    
    public void MedalDataOnDemand.setName(Medal obj, int index) {
        String name = "name_" + index;
        if (name.length() > 6) {
            name = name.substring(0, 6);
        }
        obj.setName(name);
    }
    
    public Medal MedalDataOnDemand.getSpecificMedal(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Medal obj = data.get(index);
        String id = obj.getCode_();
        return Medal.findMedal(id);
    }
    
    public Medal MedalDataOnDemand.getRandomMedal() {
        init();
        Medal obj = data.get(rnd.nextInt(data.size()));
        String id = obj.getCode_();
        return Medal.findMedal(id);
    }
    
    public boolean MedalDataOnDemand.modifyMedal(Medal obj) {
        return false;
    }
    
    public void MedalDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Medal.findMedalEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Medal' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Medal>();
        for (int i = 0; i < 10; i++) {
            Medal obj = getNewTransientMedal(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
