// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.ParticRaceDataOnDemand;
import com.atreceno.it.diaulos.domain.ParticRaceIntegrationTest;
import com.atreceno.it.diaulos.repository.ParticRaceRepository;
import com.atreceno.it.diaulos.service.ParticRaceService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticRaceIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticRaceIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticRaceIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParticRaceIntegrationTest: @Transactional;
    
    @Autowired
    ParticRaceDataOnDemand ParticRaceIntegrationTest.dod;
    
    @Autowired
    ParticRaceService ParticRaceIntegrationTest.particRaceService;
    
    @Autowired
    ParticRaceRepository ParticRaceIntegrationTest.particRaceRepository;
    
    @Test
    public void ParticRaceIntegrationTest.testCountAllParticRaces() {
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", dod.getRandomParticRace());
        long count = particRaceService.countAllParticRaces();
        Assert.assertTrue("Counter for 'ParticRace' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticRaceIntegrationTest.testFindParticRace() {
        ParticRace obj = dod.getRandomParticRace();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to provide an identifier", id);
        obj = particRaceService.findParticRace(id);
        Assert.assertNotNull("Find method for 'ParticRace' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ParticRace' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticRaceIntegrationTest.testFindAllParticRaces() {
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", dod.getRandomParticRace());
        long count = particRaceService.countAllParticRaces();
        Assert.assertTrue("Too expensive to perform a find all test for 'ParticRace', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ParticRace> result = particRaceService.findAllParticRaces();
        Assert.assertNotNull("Find all method for 'ParticRace' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ParticRace' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticRaceIntegrationTest.testFindParticRaceEntries() {
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", dod.getRandomParticRace());
        long count = particRaceService.countAllParticRaces();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ParticRace> result = particRaceService.findParticRaceEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ParticRace' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ParticRace' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticRaceIntegrationTest.testFlush() {
        ParticRace obj = dod.getRandomParticRace();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to provide an identifier", id);
        obj = particRaceService.findParticRace(id);
        Assert.assertNotNull("Find method for 'ParticRace' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticRace(obj);
        Integer currentVersion = obj.getVersion();
        particRaceRepository.flush();
        Assert.assertTrue("Version for 'ParticRace' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticRaceIntegrationTest.testUpdateParticRaceUpdate() {
        ParticRace obj = dod.getRandomParticRace();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to provide an identifier", id);
        obj = particRaceService.findParticRace(id);
        boolean modified =  dod.modifyParticRace(obj);
        Integer currentVersion = obj.getVersion();
        ParticRace merged = particRaceService.updateParticRace(obj);
        particRaceRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ParticRace' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticRaceIntegrationTest.testSaveParticRace() {
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", dod.getRandomParticRace());
        ParticRace obj = dod.getNewTransientParticRace(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ParticRace' identifier to be null", obj.getId());
        particRaceService.saveParticRace(obj);
        particRaceRepository.flush();
        Assert.assertNotNull("Expected 'ParticRace' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticRaceIntegrationTest.testDeleteParticRace() {
        ParticRace obj = dod.getRandomParticRace();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticRace' failed to provide an identifier", id);
        obj = particRaceService.findParticRace(id);
        particRaceService.deleteParticRace(obj);
        particRaceRepository.flush();
        Assert.assertNull("Failed to remove 'ParticRace' with identifier '" + id + "'", particRaceService.findParticRace(id));
    }
    
}
