// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.ParticipantDataOnDemand;
import com.atreceno.it.diaulos.domain.ParticipantIntegrationTest;
import com.atreceno.it.diaulos.repository.ParticipantRepository;
import com.atreceno.it.diaulos.service.ParticipantService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticipantIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticipantIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticipantIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParticipantIntegrationTest: @Transactional;
    
    @Autowired
    ParticipantDataOnDemand ParticipantIntegrationTest.dod;
    
    @Autowired
    ParticipantService ParticipantIntegrationTest.participantService;
    
    @Autowired
    ParticipantRepository ParticipantIntegrationTest.participantRepository;
    
    @Test
    public void ParticipantIntegrationTest.testCountAllParticipants() {
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = participantService.countAllParticipants();
        Assert.assertTrue("Counter for 'Participant' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipant() {
        Participant obj = dod.getRandomParticipant();
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = participantService.findParticipant(id);
        Assert.assertNotNull("Find method for 'Participant' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Participant' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindAllParticipants() {
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = participantService.countAllParticipants();
        Assert.assertTrue("Too expensive to perform a find all test for 'Participant', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Participant> result = participantService.findAllParticipants();
        Assert.assertNotNull("Find all method for 'Participant' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Participant' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticipantIntegrationTest.testFindParticipantEntries() {
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        long count = participantService.countAllParticipants();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Participant> result = participantService.findParticipantEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Participant' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Participant' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticipantIntegrationTest.testFlush() {
        Participant obj = dod.getRandomParticipant();
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = participantService.findParticipant(id);
        Assert.assertNotNull("Find method for 'Participant' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticipant(obj);
        Integer currentVersion = obj.getVersion();
        participantRepository.flush();
        Assert.assertTrue("Version for 'Participant' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantIntegrationTest.testUpdateParticipantUpdate() {
        Participant obj = dod.getRandomParticipant();
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = participantService.findParticipant(id);
        boolean modified =  dod.modifyParticipant(obj);
        Integer currentVersion = obj.getVersion();
        Participant merged = participantService.updateParticipant(obj);
        participantRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Participant' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticipantIntegrationTest.testSaveParticipant() {
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", dod.getRandomParticipant());
        Participant obj = dod.getNewTransientParticipant(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Participant' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Participant' identifier to be null", obj.getId());
        try {
            participantService.saveParticipant(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        participantRepository.flush();
        Assert.assertNotNull("Expected 'Participant' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticipantIntegrationTest.testDeleteParticipant() {
        Participant obj = dod.getRandomParticipant();
        Assert.assertNotNull("Data on demand for 'Participant' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Participant' failed to provide an identifier", id);
        obj = participantService.findParticipant(id);
        participantService.deleteParticipant(obj);
        participantRepository.flush();
        Assert.assertNull("Failed to remove 'Participant' with identifier '" + id + "'", participantService.findParticipant(id));
    }
    
}
