// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.ParticLapDataOnDemand;
import com.atreceno.it.diaulos.domain.ParticLapIntegrationTest;
import com.atreceno.it.diaulos.repository.ParticLapRepository;
import com.atreceno.it.diaulos.service.ParticLapService;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticLapIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticLapIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticLapIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParticLapIntegrationTest: @Transactional;
    
    @Autowired
    ParticLapDataOnDemand ParticLapIntegrationTest.dod;
    
    @Autowired
    ParticLapService ParticLapIntegrationTest.particLapService;
    
    @Autowired
    ParticLapRepository ParticLapIntegrationTest.particLapRepository;
    
    @Test
    public void ParticLapIntegrationTest.testCountAllParticLaps() {
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", dod.getRandomParticLap());
        long count = particLapService.countAllParticLaps();
        Assert.assertTrue("Counter for 'ParticLap' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticLapIntegrationTest.testFindParticLap() {
        ParticLap obj = dod.getRandomParticLap();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to provide an identifier", id);
        obj = particLapService.findParticLap(id);
        Assert.assertNotNull("Find method for 'ParticLap' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ParticLap' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticLapIntegrationTest.testFindAllParticLaps() {
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", dod.getRandomParticLap());
        long count = particLapService.countAllParticLaps();
        Assert.assertTrue("Too expensive to perform a find all test for 'ParticLap', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ParticLap> result = particLapService.findAllParticLaps();
        Assert.assertNotNull("Find all method for 'ParticLap' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ParticLap' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticLapIntegrationTest.testFindParticLapEntries() {
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", dod.getRandomParticLap());
        long count = particLapService.countAllParticLaps();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ParticLap> result = particLapService.findParticLapEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ParticLap' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ParticLap' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticLapIntegrationTest.testFlush() {
        ParticLap obj = dod.getRandomParticLap();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to provide an identifier", id);
        obj = particLapService.findParticLap(id);
        Assert.assertNotNull("Find method for 'ParticLap' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticLap(obj);
        Integer currentVersion = obj.getVersion();
        particLapRepository.flush();
        Assert.assertTrue("Version for 'ParticLap' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticLapIntegrationTest.testUpdateParticLapUpdate() {
        ParticLap obj = dod.getRandomParticLap();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to provide an identifier", id);
        obj = particLapService.findParticLap(id);
        boolean modified =  dod.modifyParticLap(obj);
        Integer currentVersion = obj.getVersion();
        ParticLap merged = particLapService.updateParticLap(obj);
        particLapRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ParticLap' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticLapIntegrationTest.testSaveParticLap() {
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", dod.getRandomParticLap());
        ParticLap obj = dod.getNewTransientParticLap(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ParticLap' identifier to be null", obj.getId());
        try {
            particLapService.saveParticLap(obj);
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        particLapRepository.flush();
        Assert.assertNotNull("Expected 'ParticLap' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticLapIntegrationTest.testDeleteParticLap() {
        ParticLap obj = dod.getRandomParticLap();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticLap' failed to provide an identifier", id);
        obj = particLapService.findParticLap(id);
        particLapService.deleteParticLap(obj);
        particLapRepository.flush();
        Assert.assertNull("Failed to remove 'ParticLap' with identifier '" + id + "'", particLapService.findParticLap(id));
    }
    
}
