// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.Event;
import com.atreceno.it.diaulos.domain.EventDataOnDemand;
import com.atreceno.it.diaulos.domain.MedalDataOnDemand;
import com.atreceno.it.diaulos.domain.ParticEvent;
import com.atreceno.it.diaulos.domain.ParticEventDataOnDemand;
import com.atreceno.it.diaulos.domain.Participant;
import com.atreceno.it.diaulos.domain.ParticipantDataOnDemand;
import com.atreceno.it.diaulos.repository.ParticEventRepository;
import com.atreceno.it.diaulos.service.ParticEventService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ParticEventDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ParticEventDataOnDemand: @Component;
    
    private Random ParticEventDataOnDemand.rnd = new SecureRandom();
    
    private List<ParticEvent> ParticEventDataOnDemand.data;
    
    @Autowired
    EventDataOnDemand ParticEventDataOnDemand.eventDataOnDemand;
    
    @Autowired
    MedalDataOnDemand ParticEventDataOnDemand.medalDataOnDemand;
    
    @Autowired
    ParticipantDataOnDemand ParticEventDataOnDemand.participantDataOnDemand;
    
    @Autowired
    ParticEventService ParticEventDataOnDemand.particEventService;
    
    @Autowired
    ParticEventRepository ParticEventDataOnDemand.particEventRepository;
    
    public ParticEvent ParticEventDataOnDemand.getNewTransientParticEvent(int index) {
        ParticEvent obj = new ParticEvent();
        setEvent(obj, index);
        setParticipant(obj, index);
        setRank(obj, index);
        setResult(obj, index);
        return obj;
    }
    
    public void ParticEventDataOnDemand.setEvent(ParticEvent obj, int index) {
        Event event = eventDataOnDemand.getRandomEvent();
        obj.setEvent(event);
    }
    
    public void ParticEventDataOnDemand.setParticipant(ParticEvent obj, int index) {
        Participant participant = participantDataOnDemand.getRandomParticipant();
        obj.setParticipant(participant);
    }
    
    public void ParticEventDataOnDemand.setRank(ParticEvent obj, int index) {
        Integer rank = new Integer(index);
        obj.setRank(rank);
    }
    
    public void ParticEventDataOnDemand.setResult(ParticEvent obj, int index) {
        String result = "result_" + index;
        obj.setResult(result);
    }
    
    public ParticEvent ParticEventDataOnDemand.getSpecificParticEvent(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        ParticEvent obj = data.get(index);
        Long id = obj.getId();
        return particEventService.findParticEvent(id);
    }
    
    public ParticEvent ParticEventDataOnDemand.getRandomParticEvent() {
        init();
        ParticEvent obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return particEventService.findParticEvent(id);
    }
    
    public boolean ParticEventDataOnDemand.modifyParticEvent(ParticEvent obj) {
        return false;
    }
    
    public void ParticEventDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = particEventService.findParticEventEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'ParticEvent' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<ParticEvent>();
        for (int i = 0; i < 10; i++) {
            ParticEvent obj = getNewTransientParticEvent(i);
            try {
                particEventService.saveParticEvent(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            particEventRepository.flush();
            data.add(obj);
        }
    }
    
}
