// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.atreceno.it.diaulos.domain;

import com.atreceno.it.diaulos.domain.ParticEventDataOnDemand;
import com.atreceno.it.diaulos.domain.ParticEventIntegrationTest;
import com.atreceno.it.diaulos.repository.ParticEventRepository;
import com.atreceno.it.diaulos.service.ParticEventService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ParticEventIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ParticEventIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ParticEventIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: ParticEventIntegrationTest: @Transactional;
    
    @Autowired
    ParticEventDataOnDemand ParticEventIntegrationTest.dod;
    
    @Autowired
    ParticEventService ParticEventIntegrationTest.particEventService;
    
    @Autowired
    ParticEventRepository ParticEventIntegrationTest.particEventRepository;
    
    @Test
    public void ParticEventIntegrationTest.testCountAllParticEvents() {
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", dod.getRandomParticEvent());
        long count = particEventService.countAllParticEvents();
        Assert.assertTrue("Counter for 'ParticEvent' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ParticEventIntegrationTest.testFindParticEvent() {
        ParticEvent obj = dod.getRandomParticEvent();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to provide an identifier", id);
        obj = particEventService.findParticEvent(id);
        Assert.assertNotNull("Find method for 'ParticEvent' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'ParticEvent' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ParticEventIntegrationTest.testFindAllParticEvents() {
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", dod.getRandomParticEvent());
        long count = particEventService.countAllParticEvents();
        Assert.assertTrue("Too expensive to perform a find all test for 'ParticEvent', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<ParticEvent> result = particEventService.findAllParticEvents();
        Assert.assertNotNull("Find all method for 'ParticEvent' illegally returned null", result);
        Assert.assertTrue("Find all method for 'ParticEvent' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ParticEventIntegrationTest.testFindParticEventEntries() {
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", dod.getRandomParticEvent());
        long count = particEventService.countAllParticEvents();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<ParticEvent> result = particEventService.findParticEventEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'ParticEvent' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'ParticEvent' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ParticEventIntegrationTest.testFlush() {
        ParticEvent obj = dod.getRandomParticEvent();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to provide an identifier", id);
        obj = particEventService.findParticEvent(id);
        Assert.assertNotNull("Find method for 'ParticEvent' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyParticEvent(obj);
        Integer currentVersion = obj.getVersion();
        particEventRepository.flush();
        Assert.assertTrue("Version for 'ParticEvent' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticEventIntegrationTest.testUpdateParticEventUpdate() {
        ParticEvent obj = dod.getRandomParticEvent();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to provide an identifier", id);
        obj = particEventService.findParticEvent(id);
        boolean modified =  dod.modifyParticEvent(obj);
        Integer currentVersion = obj.getVersion();
        ParticEvent merged = particEventService.updateParticEvent(obj);
        particEventRepository.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'ParticEvent' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ParticEventIntegrationTest.testSaveParticEvent() {
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", dod.getRandomParticEvent());
        ParticEvent obj = dod.getNewTransientParticEvent(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'ParticEvent' identifier to be null", obj.getId());
        particEventService.saveParticEvent(obj);
        particEventRepository.flush();
        Assert.assertNotNull("Expected 'ParticEvent' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ParticEventIntegrationTest.testDeleteParticEvent() {
        ParticEvent obj = dod.getRandomParticEvent();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'ParticEvent' failed to provide an identifier", id);
        obj = particEventService.findParticEvent(id);
        particEventService.deleteParticEvent(obj);
        particEventRepository.flush();
        Assert.assertNull("Failed to remove 'ParticEvent' with identifier '" + id + "'", particEventService.findParticEvent(id));
    }
    
}
